version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  unittest:
    docker:
      - image: circleci/jruby:9.2.7.0-jdk
    steps:
      - checkout
      - run:
          name: Install bundler specified in Gemfile.lock
          command: |
            gem update --system
            gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
      - restore_cache:
          keys:
            - logstash-output-scalyr-{{ checksum "Gemfile.lock" }}
            - logstash-output-scalyr-
      - run: # Install Ruby dependencies
          name: Bundle Install
          command: bundle check --path vendor/bundle || bundle install --deployment
      # Store bundle cache for Ruby dependencies
      - save_cache:
          key: logstash-output-scalyr-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run rspec in parallel
          command: |
            # gem install rspec_junit_formatter
            bundle exec rspec
            #            --profile 10 \
            #            --format RspecJunitFormatter \
            #            --out test_results/rspec.xml \
            #            --format progress \
            # $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      # Save test results for timing analysis
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test_results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for example deploy configs
  smoketest-git-dev:
    docker:
      - image: circleci/jruby:9.2.7.0-jdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout # special step to check out source code to working directory
      - run:
          name: Build gem
          command: |
            gem build logstash-output-scalyr.gemspec
            # We rename the file so we don't need to hard code version in Dockerfile
            mv logstash-output-scalyr-*.gem logstash-output-scalyr.gem
      - run:
          name: Run smoketest script which first builds another Docker Logstash image and installs our gem
          command: |
            gemfile=$(ls *.gem)
            echo "Using gemfile: ${gemfile}"
            cp $gemfile .circleci/docker/
            source .circleci/smoketest_logstash.sh yarnsh/agent-testing:latest 300 $gemfile .circleci/docker
  smoketest-rubygems-stable:
    docker:
      - image: circleci/jruby:9.2.7.0-jdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout # special step to check out source code to working directory
      - run:
          name: Download Gem from RubyGems
          command: |
            sudo apt-get update
            sudo apt-get install -y jq
            LATEST_VERSION=$(curl https://rubygems.org/api/v1/versions/logstash-output-scalyr/latest.json | jq .version | tr -d '"')
            wget https://rubygems.org/downloads/logstash-output-scalyr-${LATEST_VERSION}.gem
            # We rename the file so we don't need to hard code version in Dockerfile
            mv logstash-output-scalyr-*.gem logstash-output-scalyr.gem
      - run:
          name: Run smoketest script which first builds another Docker Logstash image and installs our gem
          command: |
            gemfile=$(ls *.gem)
            echo "Using gemfile: ${gemfile}"
            cp $gemfile .circleci/docker/
            source .circleci/smoketest_logstash.sh yarnsh/agent-testing:latest 300 $gemfile .circleci/docker

  # NOTE: We need to use large resource class since for jRuby benchmark we
  # pre-generate and store large dataset in memory
  microbenchmarks-jruby:
    docker:
      - image: circleci/jruby:9.2.7.0-jdk
    resource_class: large
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout # special step to check out source code to working directory
      - run:
          name: Run Micro Benchmarks
          command: |
            echo "Flattening and serialization util results:"
            ruby spec/benchmarks/flattening_and_serialization.rb
            echo ""
  microbenchmarks-cruby:
    docker:
      - image: cimg/ruby:2.7.1-node
    resource_class: large
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout # special step to check out source code to working directory
      - run:
          name: Run Micro Benchmarks
          command: |
            echo "Flattening and serialization util results:"
            ruby spec/benchmarks/flattening_and_serialization.rb
            echo ""

workflows:
  version: 2
  unittests-smoketests-benchmarks:
    jobs:
      - smoketest-git-dev
      - smoketest-rubygems-stable
      - unittest
      - microbenchmarks-jruby
      - microbenchmarks-cruby

  daily-stable-smoke-tests:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
       - smoketest-rubygems-stable
